version: '3.9'

services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
        POSTGRES_DB: filesystem
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin